### ISSUE TITLE
Use with headless browsers

### ISSUE THREAD

**Issue by timvol** [drevops/behat-screenshot#50]
The extension works fine with any headed browser, but when I try to use it combined with a headless browser, my browser driver (in my case gecko) always says `Error: no DISPLAY environment variable specified`
When I disable this plugin in my behat.yml everything works, but with this plugin, I cannot run my behat tests anymore. So any idea how to fix this issue?

**Comment by AlexSkrypnyk** [comment]
@timvol 
Where does your headless browser runs: locally or in Docker container? 

The `DISPLAY` variable is usually required by Selenium to run `@javascript` tests.

https://stackoverflow.com/questions/24653127/selenium-error-no-display-specified

The Docker image used to test this package already has everything setup https://github.com/drevops/behat-screenshot/blob/master/docker-compose.yml#L11 Maybe you can use it as-is.

**Comment by timvol** [comment]
@AlexSkrypnyk 

I'm using geckodriver + Firefox, but I also tested it with chromedriver + Chrome and both are telling me the same message mentioned above. Currently the drivers and the browsers are both inside the container where my Behat test runs.

**Comment by AlexSkrypnyk** [comment]
When this extension is enabled, it tries to start a browser session using one of the existing drivers. That driver would be communicating with the browser to get the session started. It is up to the browser's environment and installation to have all the tools required to be able to run it in a headless mode (like having Xvfb installed etc.).

Also, need to make sure that your Behat configuration uses the correct driver in the configuration.

For example, to test JS screenshots, this extension's own `behat.yml` uses `selenium2` driver. This driver then talks to browser through Selenium.

The driver may actually talk to browser in the headless mode around selenium. You would have to find a suitable driver for this.

See this list of supported drivers https://github.com/FriendsOfBehat/MinkExtension/tree/master/src/Behat/MinkExtension/ServiceContainer/Driver

I'm going to close this issue as it is not related to this extension directly.
