### ISSUE TITLE
symfony 7, drop unsupported symfony

### ISSUE THREAD

**Issue by tacman** [drevops/behat-screenshot#72]
Symfony only support ^5.4 || ^6.3 || ^7.0

I can make a PR to add Symfony 7, but what do you think of dropping support for unsupported versions of Symfony?

**Comment by AlexSkrypnyk** [comment]
Looking at https://endoflife.date/symfony

we should only have ^6.4 || ^7.0 and update the code accordingly 

A PR would be great! Thank you
